name: reviewdog
on: 
  pull_request:
    paths:
      - 'fern/docs/pages/**'

jobs:
  vale:
    name: runner / vale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Retrieve Changed Files
        id: files
        uses: masesgroup/retrieve-changed-files@v2
        with:
          format: 'json'

      - name: Copy Custom Styles
        run: cp -R fern/docs/pages/vale-styles $GITHUB_WORKSPACE/fern/docs/pages/.

      - name: Echo styles folder
        run: ls $GITHUB_WORKSPACE/fern/docs/pages/vale-styles

      - name: Echo .vale.ini
        run: cat $GITHUB_WORKSPACE/.vale.ini

      - name: Run Vale
        uses: errata-ai/vale-action@reviewdog
        with:
          files: ${{ steps.files.outputs.added_modified }}