name: reviewdog
on: 
  pull_request:
    paths:
      - 'fern/docs/pages/**'

jobs:
  vale:
    name: runner / vale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Determine Changed Files
        id: changed_files
        run: |
          changed_files=$(git diff --name-only HEAD^..HEAD -- 'fern/docs/pages/')
          echo "files=$changed_files" >> $GITHUB_ENV

      - name: Run Vale
        uses: errata-ai/vale-action@reviewdog
        with:
          files: ${{ env.files }}